---
title: "Car recognition"
author: "JD"
date: "2023-05-27"
output: html_document
---

```{r}

#install.packages('tidyverse')
#install.packages('keras')
#install.packages('tensorflow')
#install.packages('reticulate')

```


```{r}

library(tidyverse)
library(keras)
library(tensorflow)
library(reticulate)

```

```{r}
#install_tensorflow(extra_packages="pillow")
#install_keras()
```


```{r}
setwd("./")
label_list <- dir("a/")
output_n <- length(label_list)
save(label_list, file="label_list.R")

```

```{r}
width <- 150
height<- 150
target_size <- c(width, height)
rgb <- 3 #color channels
```

```{r}
path_train <- "./a/"
train_data_gen <- image_data_generator(rescale = 1/255, 
  validation_split = .2)

```

```{r}
train_images <- flow_images_from_directory(path_train,
  train_data_gen,
  subset = 'training',
  target_size = target_size,
  class_mode = "categorical",
  shuffle=F,
  classes = label_list,
  seed = 2021)
```

```{r}
validation_images <- flow_images_from_directory(path_train,
 train_data_gen, 
  subset = 'validation',
  target_size = target_size,
  class_mode = "categorical",
  classes = label_list,
  seed = 2021)
```

```{r}

table(train_images$classes)

```

```{r}
mod_base <- application_xception(weights = 'imagenet', 
   include_top = FALSE, input_shape = c(width, height, 3))
freeze_weights(mod_base) 
```

```{r}
model_function <- function(learning_rate = 0.001, 
  dropoutrate=0.2, n_dense=1024){
  
  k_clear_session()
  
  model <- keras_model_sequential() %>%
    mod_base %>% 
    layer_global_average_pooling_2d() %>% 
    layer_dense(units = n_dense) %>%
    layer_activation("relu") %>%
    layer_dropout(dropoutrate) %>%
    layer_dense(units=output_n, activation="softmax")
  
  model %>% compile(
    loss = "categorical_crossentropy",
    optimizer = optimizer_adam(lr = learning_rate),
    metrics = "accuracy"
  )
  
  return(model)
  
}
```

```{r}

model <- model_function()
model

```

```{r}
batch_size <- 32
epochs <- 6
hist <- model %>% fit_generator(
  train_images,
  steps_per_epoch = train_images$n %/% batch_size, 
  epochs = epochs, 
  validation_data = validation_images,
  validation_steps = validation_images$n %/% batch_size,
  verbose = 2
)
```
```{r}
path_test <- "./b/"
test_data_gen <- image_data_generator(rescale = 1/255)
test_images <- flow_images_from_directory(path_test,
   test_data_gen,
   target_size = target_size,
   class_mode = "categorical",
   classes = label_list,
   shuffle = F,
   seed = 2021)
model %>% evaluate_generator(test_images, 
                     steps = test_images$n)
```

```{r}

get_probability <- function(path) {
  test_image <- image_load(path = path, target_size = target_size)
  x <- image_to_array(test_image)
  x <- array_reshape(x, c(1, dim(x)))
  x <- x/255
  pred <- model %>% predict(x)
  pred <- data.frame("Parking lot" = label_list, "Probability" = t(pred))
  pred <- pred[order(pred$Probability, decreasing=T),][1:5,]
  pred$Probability <- paste(format(100*pred$Probability,2),"%")
  
  return(pred)
  
}

```

```{r}
get_probability('test/busy.png')
get_probability('test/free.png')
```

